    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 20 TO 2000 STEP 100
    SOUND i%, i% / 10000
    NEXT i%
    FOR i% = 2000 TO 40 STEP -100
    SOUND i%, i% / 10000
    NEXT i%

